config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  post '/add_item_cart', to: 'carts#add_to_cart'
  get '/get_estate', to: 'checkout#estate'
  get 'get_station', to: 'checkout#station'
  resources :products
  resources :merchant_accounts
  resources :checkout, only: [:index]
  resources :addresses
  resource :cart, except: [:create]
end

app/models/account.rb
class Account < ApplicationRecord
    has_many :merchant_accounts
    has_many :orders
    belongs_to :user
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :addressable, polymorphic: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :estates, dependent: :destroy
    has_many :pick_up_stations, through: :estates
end

app/models/estate.rb
class Estate < ApplicationRecord
  belongs_to :city
  has_many :pick_up_stations, dependent: :destroy
end

app/models/merchant_account.rb
class MerchantAccount < ApplicationRecord
  belongs_to :account
  has_many :products
  has_many :ordered_items, through: :products
  after_create :update_account_type

  def update_account_type
    account = Account.find(self.account_id)
    account.update(merchant_account: true)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :account
  has_many :ordered_items
  has_one :address, as: :addressable
  
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/pick_up_station.rb
class PickUpStation < ApplicationRecord
  belongs_to :estate
  
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :merchant_account
  has_many :ordered_items
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :account
  has_many :addresses, as: :addressable
  after_create :create_account

  def create_account
    Account.new({user_id: self.id}).save
  end

  def has_merchant_account?
    return false if self.account.nil?
    self.account.merchant_account
  end
  
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    def show
        @order = Order.find(session[:order_id])  
    end

    def add_to_cart
        
        if session.key?(:order_id)
            order = Order.find(session[:order_id])
            order.ordered_items.build(product_id: params[:id]).save
        else
            account = current_user.account
            @order = account.orders.build()
            if @order.save
                session[:order_id] = @order.id
                @order.ordered_items.build(product_id: params[:id]).save
            end
            
        end
    end
    
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

    def index
        @address = Address.new
        @cities = City.all
    end

    def estate
        city = City.find_by(city_name: params[:city_name])
        @estates = city.estates
        @estate_name = []
        @estates.each do |estate|
            @estate_name << estate.estate_name
        end
        render json: {estates: @estate_name}
    end

    def station
        estate = Estate.find_by(estate_name: params[:estate_name])
        @stations = estate.pick_up_stations
        @station_name = []
        @stations.each do |station|
            @station_name << {name: station.station_name, street: station.street, estate: estate.estate_name}
        end
        render json: {stations: @station_name}
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def new
        @product = Product.new
    end

    def create
        #come back and fix the logic
        account = current_user.account
        merchant = account.merchant_accounts.first
        @product = merchant.products.build(product_params)
        if @product.save
            redirect_to @product, notice: "Design successfully added."
        else
            render 'new'
        end
    end

    def index
        @products = Product.all
    end

    def show
        @product = Product.find(params[:id])
    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            redirect_to @product, notice: "Product successfully updated"
        else
            render 'edit'
        end
    end

    def destroy

    end

    private

    def product_params
        params.require(:product).permit(:price, :image)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/merchant_helper.rb
module MerchantHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Designscape</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= render 'shared/navigation' %>
    <%= yield %>
  </body>
</html>

app/views/shared/_delivery.html.erb
<div>
    <h2>Delivery method</h2>
    
    <p>How do you want your order delivered ?</p>
    <div class="delivery-options ">
        <div class="station">
            <%= form.radio_button :delivery_option, "Pickup Station"%>
            <%= form.label :delivery_option_station, "Pickup Station"%>
            <button class="btn btn-success " id="trigger-modal">Select pick up station</button>
            <div class="modal" id="myModal">
                <div class="modal-content">
                    <span class="close">&times;</span>
                <div class="row">
              <div class="col-md-5 mb-3">
                <%= form.label :city, "City"%>
                
                <%= form.collection_select :city_id, cities.order(:city_name), :city_name, :city_name, class: "custom-select d-block w-100", id: "delivery-city" %>
                <div class="invalid-feedback">
                  Please select a valid country.
                </div>
              </div>
              <div class="col-md-4 mb-3">
                <label for="state">Estate</label>
                <select class="custom-select d-block w-100" id="delivery-estate" name= "delivery-estate" required>
                  
                </select>
                <div class="invalid-feedback">
                  Please provide a valid state.
                </div>
              </div>
              <div id="pick-up-station">
                
              </div>
                          </div>
                </div>
            </div>
        </div>
        <div class="home-address">
            <%= form.radio_button :delivery_option, "Home"%>
            <%= form.label :delivery_option_home, "Deliver to your home or office"%>
        </div>
    </div>
</div>

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <div class="container-fluid">
    <a class="navbar-brand" href="#">Navbar</a>
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/">Home</a>
        </li>
        <% if user_signed_in? && current_user.has_merchant_account?%>
          <li class="nav-item">
            <%= link_to "Dashboard", merchant_accounts_path, class: "nav-link" %>
          </li>
        <% end %>
        
        <li class="nav-item dropdown">
          <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
            Dropdown
          </a>
          <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
            <li><a class="dropdown-item" href="#">Action</a></li>
            <li><a class="dropdown-item" href="#">Another action</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="#">Something else here</a></li>
          </ul>
        </li>
        <li class="nav-item">
          <%= link_to "Sell on designscape", new_merchant_account_path, class: "nav-link"%>
        </li>
      </ul>
      <ul class="float-right navbar-nav">
        <% unless user_signed_in? %>
        <li class="nav-item">
          <%= link_to "Sign up", new_user_registration_path, class: "nav-link" %>
        </li>
        
        <li class="nav-item"><%= link_to "Log in", new_user_session_path, class: "nav-link" %></li>
        <% end %>

        <% if user_signed_in? %>
        <li class="nav-item"><%= link_to "Log out", destroy_user_session_path, method: :delete,class: "nav-link" %></li>
        <% end %>
        <li>
          <%= link_to cart_path, class: "position-relative" do %>
            <%= image_tag "shopping-cart.png", class: "shopping-cart"%>
            <span id= "cart-counter" class="position-absolute top-0 start-100 translate-middle badge border border-light rounded-circle bg-danger p-2">0</span>
          <% end %>
        </li>
      </ul>
    </div>
  </div>
</nav>