config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  post '/add_item_cart', to: 'carts#add_to_cart'
  get '/get_estate', to: 'checkout#estate'
  get 'get_station', to: 'checkout#station'
  resources :products
  resources :merchant_accounts
  resources :checkout, only: [:index]
  resources :addresses
  resource :cart, except: [:create]
end

app/models/account.rb
class Account < ApplicationRecord
    has_many :merchant_accounts
    has_many :orders
    belongs_to :user
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :addressable, polymorphic: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :estates, dependent: :destroy
    has_many :pick_up_stations, through: :estates
end

app/models/estate.rb
class Estate < ApplicationRecord
  belongs_to :city
  has_many :pick_up_stations, dependent: :destroy
end

app/models/merchant_account.rb
class MerchantAccount < ApplicationRecord
  belongs_to :account
  has_many :products
  has_many :ordered_items, through: :products
  after_create :update_account_type

  def update_account_type
    account = Account.find(self.account_id)
    account.update(merchant_account: true)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :account
  has_many :ordered_items
  has_one :address, as: :addressable
  
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/pick_up_station.rb
class PickUpStation < ApplicationRecord
  belongs_to :estate
  
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :merchant_account
  has_many :ordered_items
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :account
  has_many :addresses, as: :addressable
  after_create :create_account

  def create_account
    Account.new({user_id: self.id}).save
  end

  def has_merchant_account?
    return false if self.account.nil?
    self.account.merchant_account
  end
  
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

    def create
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    def show
        @order = Order.find(session[:order_id])  
    end

    def add_to_cart
        
        if session.key?(:order_id)
            order = Order.find(session[:order_id])
            order.ordered_items.build(product_id: params[:id]).save
        else
            account = current_user.account
            @order = account.orders.build()
            if @order.save
                session[:order_id] = @order.id
                @order.ordered_items.build(product_id: params[:id]).save
            end
            
        end
    end
    
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

    def index
        @address = Address.new
        @cities = City.all
    end

    def estate
        city = City.find_by(city_name: params[:city_name])
        @estates = city.estates
        @estate_name = []
        @estates.each do |estate|
            @estate_name << estate.estate_name
        end
        render json: {estates: @estate_name}
    end

    def station
        estate = Estate.find_by(estate_name: params[:estate_name])
        @stations = estate.pick_up_stations
        @station_name = []
        @stations.each do |station|
            @station_name << {name: station.station_name, street: station.street, estate: estate.estate_name}
        end
        render json: {stations: @station_name}
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def new
        @product = Product.new
    end

    def create
        #come back and fix the logic
        account = current_user.account
        merchant = account.merchant_accounts.first
        @product = merchant.products.build(product_params)
        if @product.save
            redirect_to @product, notice: "Design successfully added."
        else
            render 'new'
        end
    end

    def index
        @products = Product.all
    end

    def show
        @product = Product.find(params[:id])
    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            redirect_to @product, notice: "Product successfully updated"
        else
            render 'edit'
        end
    end

    def destroy

    end

    private

    def product_params
        params.require(:product).permit(:price, :image)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/merchant_helper.rb
module MerchantHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/address/_address.html.erb
<%= form_with model: address, :html => {:id => "checkout-form"} do |form| %>
            <div class="row">
              <div class="col-md-6 mb-3">
                <label for="firstName">First name</label>
                <input type="text" class="form-control" id="firstName" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid first name is required.
                </div>
              </div>
              <div class="col-md-6 mb-3">
                <label for="lastName">Last name</label>
                <input type="text" class="form-control" id="lastName" placeholder="" value="" required>
                <div class="invalid-feedback">
                  Valid last name is required.
                </div>
              </div>
            </div>

           
            <div class="row">
              <div class="col-md-5 mb-3">
                <%= form.label :city, "City"%>
                
                <%= form.collection_select :city, cities.order(:city_name), :city_name ,:city_name, class: "custom-select d-block w-100" %>
                <div class="invalid-feedback">
                  Please select a valid country.
                </div>
              </div>
              <div class="col-md-4 mb-3">
                <label for="state">Estate</label>
                <select class="custom-select d-block w-100" id="estate" name= "estate" required>
                  
                </select>
                <div class="invalid-feedback">
                  Please provide a valid state.
                </div>
              </div>
            </div>
            <div class="mb-3">
            <%= form.label :street, "Street"%>
            <%= form.text_field :street, class: "form-control", placeholder: "Main St"%>
            <div class="invalid-feedback">
              Please enter your shipping address.
            </div>
          </div>

          <div class="mb-3">
            <%= form.label :apartment, "Apartment"%>
            <%= form.text_field :apartment, class: "form-control", placeholder: "Apartment or suite" %>
        
          </div>
            <hr class="mb-4">
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="same-address">
              <label class="custom-control-label" for="same-address">Shipping address is the same as my billing address</label>
            </div>
            <div class="custom-control custom-checkbox">
              <input type="checkbox" class="custom-control-input" id="save-info">
              <label class="custom-control-label" for="save-info">Save this information for next time</label>
            </div>
            <hr class="mb-4">
            <%= render partial: 'shared/delivery', locals: {form: form, cities: @cities} %>
            
            <hr class="mb-4">
          <button class= "btn btn-primary btn-lg" onclick="checkOutFormSubmit()">Proceed to next step</button>

           
           
    
<% end %>

app/views/cart/index.html.erb
<h1>This is the cart all items will be listed here</h1>

app/views/carts/add_to_cart.js.erb
var cartCounter = document.querySelector("#cart-counter")
function trackCartCounter(){
    let items = parseInt(cartCounter.innerText)
    items += 1
    cartCounter.innerHTML = items
    
}

trackCartCounter();

app/views/carts/show.html.erb
<h1>This is the cart all items will be listed here</h1>

<p><%= @order.id%></p>
<p><%= @order.ordered_items.count%></p>
<%= link_to "Proceed to checkout", checkout_index_path , class: "btn btn-lg btn-success"%>

app/views/checkout/index.html.erb
    <div class="container">
      <div class="row">
        <div class="col-md-4 order-md-2 mb-4">
          <h4 class="d-flex justify-content-between align-items-center mb-3">
            <span class="text-muted">Your cart</span>
            <span class="badge badge-secondary badge-pill">3</span>
          </h4>
          <ul class="list-group mb-3">
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Product name</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$12</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Second product</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$8</span>
            </li>
            <li class="list-group-item d-flex justify-content-between lh-condensed">
              <div>
                <h6 class="my-0">Third item</h6>
                <small class="text-muted">Brief description</small>
              </div>
              <span class="text-muted">$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between bg-light">
              <div class="text-success">
                <h6 class="my-0">Promo code</h6>
                <small>EXAMPLECODE</small>
              </div>
              <span class="text-success">-$5</span>
            </li>
            <li class="list-group-item d-flex justify-content-between">
              <span>Total (USD)</span>
              <strong>$20</strong>
            </li>
          </ul>

          <form class="card p-2">
            <div class="input-group">
              <input type="text" class="form-control" placeholder="Promo code">
              <div class="input-group-append">
                <button type="submit" class="btn btn-secondary">Redeem</button>
              </div>
            </div>
          </form>
        </div>
        <div class="col-md-8 order-md-1">
          <h4 class="mb-3">Billing address</h4>
          <div id="address">
            <%= render partial: "address/address", locals: {address: @address, cities: @cities}%>
          </div>
        
        </div>
      </div>

      <footer class="my-5 pt-5 text-muted text-center text-small">
        <p class="mb-1">&copy; 2017-2018 Company Name</p>
        <ul class="list-inline">
          <li class="list-inline-item"><a href="#">Privacy</a></li>
          <li class="list-inline-item"><a href="#">Terms</a></li>
          <li class="list-inline-item"><a href="#">Support</a></li>
        </ul>
      </footer>


    </div>