config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root to: 'products#index'
  post '/add_item_cart', to: 'carts#add_to_cart'
  get '/get_estate', to: 'checkout#estate'
  get 'get_station', to: 'checkout#station'
  resources :products
  resources :merchant_accounts
  resources :checkout, only: [:index]
  resources :addresses
  resource :cart, except: [:create]
end

app/models/account.rb
class Account < ApplicationRecord
    has_many :merchant_accounts
    has_many :orders
    belongs_to :user
end

app/models/address.rb
class Address < ApplicationRecord
    belongs_to :addressable, polymorphic: true
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/city.rb
class City < ApplicationRecord
    has_many :estates, dependent: :destroy
    has_many :pick_up_stations, through: :estates
end

app/models/estate.rb
class Estate < ApplicationRecord
  belongs_to :city
  has_many :pick_up_stations, dependent: :destroy
end

app/models/merchant_account.rb
class MerchantAccount < ApplicationRecord
  belongs_to :account
  has_many :products
  has_many :ordered_items, through: :products
  after_create :update_account_type

  def update_account_type
    account = Account.find(self.account_id)
    account.update(merchant_account: true)
  end
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :account
  has_many :ordered_items
  has_one :address, as: :addressable
  
end

app/models/ordered_item.rb
class OrderedItem < ApplicationRecord
  belongs_to :order
  belongs_to :product
end

app/models/pick_up_station.rb
class PickUpStation < ApplicationRecord
  belongs_to :estate
  
end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :merchant_account
  has_many :ordered_items
  has_one_attached :image
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :account
  has_many :addresses, as: :addressable
  after_create :create_account

  def create_account
    Account.new({user_id: self.id}).save
  end

  def has_merchant_account?
    return false if self.account.nil?
    self.account.merchant_account
  end
  
end

app/controllers/addresses_controller.rb
class AddressesController < ApplicationController

    def create
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController

    def show
        @order = Order.find(session[:order_id])  
    end

    def add_to_cart
        
        if session.key?(:order_id)
            order = Order.find(session[:order_id])
            order.ordered_items.build(product_id: params[:id]).save
        else
            account = current_user.account
            @order = account.orders.build()
            if @order.save
                session[:order_id] = @order.id
                @order.ordered_items.build(product_id: params[:id]).save
            end
            
        end
    end
    
end

app/controllers/checkout_controller.rb
class CheckoutController < ApplicationController

    def index
        @address = Address.new
        @cities = City.all
    end

    def estate
        city = City.find_by(city_name: params[:city_name])
        @estates = city.estates
        @estate_name = []
        @estates.each do |estate|
            @estate_name << estate.estate_name
        end
        render json: {estates: @estate_name}
    end

    def station
        estate = Estate.find_by(estate_name: params[:estate_name])
        @stations = estate.pick_up_stations
        @station_name = []
        @stations.each do |station|
            @station_name << {name: station.station_name, street: station.street, estate: estate.estate_name}
        end
        render json: {stations: @station_name}
    end
end

app/controllers/merchant_accounts_controller.rb
class MerchantAccountsController < ApplicationController
    
    def new
        @merchant = MerchantAccount.new
    end

    def create
        @account = current_user.account
        @merchant = @account.merchant_accounts.build(merchant_params)

        if @merchant.save
            redirect_to merchant_accounts_path, notice: "Merchant account successfully created"
        else
            render 'new'
        end
    end

    def index
    end

    private

    def merchant_params
        params.require(:merchant_account).permit(:account_name)
    end
    

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController

    def new
        @product = Product.new
    end

    def create
        #come back and fix the logic
        account = current_user.account
        merchant = account.merchant_accounts.first
        @product = merchant.products.build(product_params)
        if @product.save
            redirect_to @product, notice: "Design successfully added."
        else
            render 'new'
        end
    end

    def index
        @products = Product.all
    end

    def show
        @product = Product.find(params[:id])
    end

    def edit
        @product = Product.find(params[:id])
    end

    def update
        @product = Product.find(params[:id])
        if @product.update(product_params)
            redirect_to @product, notice: "Product successfully updated"
        else
            render 'edit'
        end
    end

    def destroy

    end

    private

    def product_params
        params.require(:product).permit(:price, :image)
    end
end

app/helpers/addresses_helper.rb
module AddressesHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/checkout_helper.rb
module CheckoutHelper
end

app/helpers/merchant_helper.rb
module MerchantHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/edit.html.erb
<p>Edit the product here !!</p>
<%= form_with model: @product do |form| %>
    <%= form.label :price, "Price" %>
    <%= form.text_field :price%>
    <%= form.file_field :image%>
    <%= form.submit "Create" %>
<% end %>

app/views/products/index.html.erb
<main role="main">
      <div class="album py-5 bg-light">
        <div class="container">
          <div class="row">
          <% @products.each do |product|%>
            <div class="col-md-4">
              <div class="card mb-4 box-shadow">
                  <% if product.image.attached?%>
                    <%= image_tag product.image%>
                  <% end %>
                  <p class="card-text">This is a wider card with supporting text below as a natural lead-in to additional content. This content is a little bit longer.</p>
                  <div class="d-flex justify-content-between align-items-center">
                    <div class="btn-group">
                      <%= link_to add_item_cart_path({id: product.id}), remote: true, method: :post do %>
                        <button type="button" class="btn btn-sm btn-outline-secondary">Add to cart</button>
                      <% end %>
                      <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
                    </div>
                    <small class="text-muted">Ksh.<%= product.price%></small>
                  </div>
                </div>
              </div>
            </div>
          <% end %>
          </div>
        </div>
      </div>
    </main>

app/views/products/new.html.erb
<%= form_with model: @product do |form| %>
    <%= form.label :price, "Price" %>
    <%= form.text_field :price%>
    <%= form.file_field :image%>
    <%= form.submit "Create" %>
<% end %>

app/views/products/show.html.erb
<p>the product will be shown here after being created</p>

<p>this is the pae the user will see if they click in the image</p>

<p><%= @product.price%></p>

<%= image_tag @product.image%>

<%= link_to "Edit", edit_product_path , class: "btn btn-primary"%>